package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlbumRatingId generated by hbm2java
 */
@Embeddable
public class AlbumRatingId implements java.io.Serializable {

	private String userId;
	private String albumId;
	private Integer albumRating;

	public AlbumRatingId() {
	}

	public AlbumRatingId(String userId, String albumId, Integer albumRating) {
		this.userId = userId;
		this.albumId = albumId;
		this.albumRating = albumRating;
	}

	@Column(name = "user_id", length = 15)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "album_id", length = 15)
	public String getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(String albumId) {
		this.albumId = albumId;
	}

	@Column(name = "album_rating")
	public Integer getAlbumRating() {
		return this.albumRating;
	}

	public void setAlbumRating(Integer albumRating) {
		this.albumRating = albumRating;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumRatingId))
			return false;
		AlbumRatingId castOther = (AlbumRatingId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getAlbumId() == castOther.getAlbumId()) || (this
						.getAlbumId() != null && castOther.getAlbumId() != null && this
						.getAlbumId().equals(castOther.getAlbumId())))
				&& ((this.getAlbumRating() == castOther.getAlbumRating()) || (this
						.getAlbumRating() != null
						&& castOther.getAlbumRating() != null && this
						.getAlbumRating().equals(castOther.getAlbumRating())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getAlbumId() == null ? 0 : this.getAlbumId().hashCode());
		result = 37
				* result
				+ (getAlbumRating() == null ? 0 : this.getAlbumRating()
						.hashCode());
		return result;
	}

}
