package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlbumsPurchasedId generated by hbm2java
 */
@Embeddable
public class AlbumsPurchasedId implements java.io.Serializable {

	private String userId;
	private String albumId;

	public AlbumsPurchasedId() {
	}

	public AlbumsPurchasedId(String userId, String albumId) {
		this.userId = userId;
		this.albumId = albumId;
	}

	@Column(name = "user_id", length = 15)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "album_id", length = 15)
	public String getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(String albumId) {
		this.albumId = albumId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlbumsPurchasedId))
			return false;
		AlbumsPurchasedId castOther = (AlbumsPurchasedId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getAlbumId() == castOther.getAlbumId()) || (this
						.getAlbumId() != null && castOther.getAlbumId() != null && this
						.getAlbumId().equals(castOther.getAlbumId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getAlbumId() == null ? 0 : this.getAlbumId().hashCode());
		return result;
	}

}
