package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ArtistRating generated by hbm2java
 */
@Entity
@Table(name = "artist_rating", catalog = "songrecosystem")
public class ArtistRating implements java.io.Serializable {

	private ArtistRatingId id;
	private SongArtists songArtists;
	private UserData userData;

	public ArtistRating() {
	}

	public ArtistRating(ArtistRatingId id) {
		this.id = id;
	}

	public ArtistRating(ArtistRatingId id, SongArtists songArtists,
			UserData userData) {
		this.id = id;
		this.songArtists = songArtists;
		this.userData = userData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", length = 15)),
			@AttributeOverride(name = "artistId", column = @Column(name = "artist_id", length = 15)),
			@AttributeOverride(name = "artistRating", column = @Column(name = "artist_rating")) })
	public ArtistRatingId getId() {
		return this.id;
	}

	public void setId(ArtistRatingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "artist_id", insertable = false, updatable = false)
	public SongArtists getSongArtists() {
		return this.songArtists;
	}

	public void setSongArtists(SongArtists songArtists) {
		this.songArtists = songArtists;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", insertable = false, updatable = false)
	public UserData getUserData() {
		return this.userData;
	}

	public void setUserData(UserData userData) {
		this.userData = userData;
	}

}
