package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genre", catalog = "songrecosystem")
public class Genre implements java.io.Serializable {

	private String genreId;
	private String genreName;
	private Set<SongArtists> songArtistses = new HashSet<SongArtists>(0);
	private Set<SongData> songDatas = new HashSet<SongData>(0);
	private Set<SongAlbums> songAlbumses = new HashSet<SongAlbums>(0);

	public Genre() {
	}

	public Genre(String genreId) {
		this.genreId = genreId;
	}

	public Genre(String genreId, String genreName,
			Set<SongArtists> songArtistses, Set<SongData> songDatas,
			Set<SongAlbums> songAlbumses) {
		this.genreId = genreId;
		this.genreName = genreName;
		this.songArtistses = songArtistses;
		this.songDatas = songDatas;
		this.songAlbumses = songAlbumses;
	}

	@Id
	@Column(name = "genre_id", unique = true, nullable = false, length = 15)
	public String getGenreId() {
		return this.genreId;
	}

	public void setGenreId(String genreId) {
		this.genreId = genreId;
	}

	@Column(name = "genre_name", length = 20)
	public String getGenreName() {
		return this.genreName;
	}

	public void setGenreName(String genreName) {
		this.genreName = genreName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<SongArtists> getSongArtistses() {
		return this.songArtistses;
	}

	public void setSongArtistses(Set<SongArtists> songArtistses) {
		this.songArtistses = songArtistses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<SongData> getSongDatas() {
		return this.songDatas;
	}

	public void setSongDatas(Set<SongData> songDatas) {
		this.songDatas = songDatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genre")
	public Set<SongAlbums> getSongAlbumses() {
		return this.songAlbumses;
	}

	public void setSongAlbumses(Set<SongAlbums> songAlbumses) {
		this.songAlbumses = songAlbumses;
	}

}
