package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserSecurityId generated by hbm2java
 */
@Embeddable
public class UserSecurityId implements java.io.Serializable {

	private String secureUserId;
	private String secureLoginName;
	private String securePassword;

	public UserSecurityId() {
	}

	public UserSecurityId(String secureUserId, String secureLoginName,
			String securePassword) {
		this.secureUserId = secureUserId;
		this.secureLoginName = secureLoginName;
		this.securePassword = securePassword;
	}

	@Column(name = "secure_user_id", length = 15)
	public String getSecureUserId() {
		return this.secureUserId;
	}

	public void setSecureUserId(String secureUserId) {
		this.secureUserId = secureUserId;
	}

	@Column(name = "secure_login_name", length = 15)
	public String getSecureLoginName() {
		return this.secureLoginName;
	}

	public void setSecureLoginName(String secureLoginName) {
		this.secureLoginName = secureLoginName;
	}

	@Column(name = "secure_password", length = 15)
	public String getSecurePassword() {
		return this.securePassword;
	}

	public void setSecurePassword(String securePassword) {
		this.securePassword = securePassword;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserSecurityId))
			return false;
		UserSecurityId castOther = (UserSecurityId) other;

		return ((this.getSecureUserId() == castOther.getSecureUserId()) || (this
				.getSecureUserId() != null
				&& castOther.getSecureUserId() != null && this
				.getSecureUserId().equals(castOther.getSecureUserId())))
				&& ((this.getSecureLoginName() == castOther
						.getSecureLoginName()) || (this.getSecureLoginName() != null
						&& castOther.getSecureLoginName() != null && this
						.getSecureLoginName().equals(
								castOther.getSecureLoginName())))
				&& ((this.getSecurePassword() == castOther.getSecurePassword()) || (this
						.getSecurePassword() != null
						&& castOther.getSecurePassword() != null && this
						.getSecurePassword().equals(
								castOther.getSecurePassword())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSecureUserId() == null ? 0 : this.getSecureUserId()
						.hashCode());
		result = 37
				* result
				+ (getSecureLoginName() == null ? 0 : this.getSecureLoginName()
						.hashCode());
		result = 37
				* result
				+ (getSecurePassword() == null ? 0 : this.getSecurePassword()
						.hashCode());
		return result;
	}

}
