package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserPlaycountId generated by hbm2java
 */
@Embeddable
public class UserPlaycountId implements java.io.Serializable {

	private String userId;
	private String songId;
	private Integer songPlayCount;

	public UserPlaycountId() {
	}

	public UserPlaycountId(String userId, String songId, Integer songPlayCount) {
		this.userId = userId;
		this.songId = songId;
		this.songPlayCount = songPlayCount;
	}

	@Column(name = "user_id", length = 15)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "song_id", length = 15)
	public String getSongId() {
		return this.songId;
	}

	public void setSongId(String songId) {
		this.songId = songId;
	}

	@Column(name = "song_playCount")
	public Integer getSongPlayCount() {
		return this.songPlayCount;
	}

	public void setSongPlayCount(Integer songPlayCount) {
		this.songPlayCount = songPlayCount;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserPlaycountId))
			return false;
		UserPlaycountId castOther = (UserPlaycountId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this
				.getUserId() != null && castOther.getUserId() != null && this
				.getUserId().equals(castOther.getUserId())))
				&& ((this.getSongId() == castOther.getSongId()) || (this
						.getSongId() != null && castOther.getSongId() != null && this
						.getSongId().equals(castOther.getSongId())))
				&& ((this.getSongPlayCount() == castOther.getSongPlayCount()) || (this
						.getSongPlayCount() != null
						&& castOther.getSongPlayCount() != null && this
						.getSongPlayCount()
						.equals(castOther.getSongPlayCount())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result
				+ (getSongId() == null ? 0 : this.getSongId().hashCode());
		result = 37
				* result
				+ (getSongPlayCount() == null ? 0 : this.getSongPlayCount()
						.hashCode());
		return result;
	}

}
