package newEntities;

// Generated Oct 20, 2012 3:07:20 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserSecurity generated by hbm2java
 */
@Entity
@Table(name = "user_security", catalog = "songrecosystem")
public class UserSecurity implements java.io.Serializable {

	private UserSecurityId id;
	private UserData userData;

	public UserSecurity() {
	}

	public UserSecurity(UserSecurityId id) {
		this.id = id;
	}

	public UserSecurity(UserSecurityId id, UserData userData) {
		this.id = id;
		this.userData = userData;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "secureUserId", column = @Column(name = "secure_user_id", length = 15)),
			@AttributeOverride(name = "secureLoginName", column = @Column(name = "secure_login_name", length = 15)),
			@AttributeOverride(name = "securePassword", column = @Column(name = "secure_password", length = 15)) })
	public UserSecurityId getId() {
		return this.id;
	}

	public void setId(UserSecurityId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "secure_user_id", insertable = false, updatable = false)
	public UserData getUserData() {
		return this.userData;
	}

	public void setUserData(UserData userData) {
		this.userData = userData;
	}

}
